version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: aibee3
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
