#### create category
POST http://localhost:3033/api/v1/categories
Content-Type: application/json

{
"name": "c4",
"discount": 20
}

#### create category
POST http://localhost:3033/api/v1/categories
Content-Type: application/json

{
"parent": "6295107dd9bc5b7e56434c8a",
"name": "c5",
"discount": 30
}

#### create category
POST http://localhost:3033/api/v1/categories
Content-Type: application/json

{
"parent": "6295108bd9bc5b7e56434c8c",
"name": "c7",
"discount": 400
}

#### create product
POST http://localhost:3033/api/v1/products
Content-Type: application/json

{
  "code": "p9",
  "parent": "62951328a92e838165e370e4",
  "name": "p9"
}

#### get discount
GET http://localhost:3033/api/v1/products/discount?name=p9&code=p9&amount=1000
Content-Type: application/json
