#### create category
POST http://localhost:3033/api/v1/categories
Content-Type: application/json

{
"name": "c1",
"discount": 20
}

#### create category
POST http://localhost:3033/api/v1/categories
Content-Type: application/json

{
"parent": "6294f3175436f68a96708090",
"name": "c2",
"discount": 30
}

#### create product
POST http://localhost:3033/api/v1/products
Content-Type: application/json

{
  "code": "p4",
  "parent": "6294f3265436f68a96708092",
  "name": "p4"
}

#### get discount
GET http://localhost:3033/api/v1/products/discount?name=p4&code=p4&amount=1000
Content-Type: application/json
